defaultEntryPoints = ["https","http"]

[entryPoints]
  [entryPoints.dashboard]
    address = ":8080"
#    [entryPoints.dashboard.auth.basic]
#      users = ["user:password"]
  [entryPoints.http]
    address = ":80"
    [entryPoints.http.redirect]
      entryPoint = "https"
  [entryPoints.https]
    address = ":443"
  [entryPoints.https.tls]
    [[entryPoints.https.tls.certificates]]
      certFile = "/ssl/example.com.pem"
      keyFile = "/ssl/example.com.key"

[api]
entrypoint="dashboard"
#debug = true

[docker]
domain = "example.com"
watch = true
network = "gitlab"
exposedbydefault = false
